### ISSUE TITLE
Error 429 : Too many requests

### ISSUE THREAD

**Issue by n1trob4ct3r** [duttaditya18/insta-stalk#2]
We need something to bypass that check.
I tried `headers = {'User-agent': 'Mozilla/5.0 (Android 4.4; Mobile; rv:41.0) Gecko/41.0 Firefox/41.0'}
` but that only works with GET requests.
I think we'll have to edit the instaloader code.

**Comment by duttaditya18** [comment]
@n1trob4ct3r We don't need the headers. Instaloader works perfectly.

This is the code I made for downloading the whole library of the Apoorva : 
```python
import json
import instaloader

# id.json with "username" and "password"
with open('id.json') as json_data:
    d = json.load(json_data)

# Get instance
L = instaloader.Instaloader()

# Optionally, login or load session
L.login(d["username"], d["password"])

profile = instaloader.Profile.from_username(L.context, "apooorvaa_")

for post in profile.get_posts():
    L.download_post(post, target=profile.username)

# fast_update=True doesn't work for some reason. If it did, it would only download the stuff that it doesn't has. It only works in stories.
```

**Comment by duttaditya18** [comment]
The same can easily be done for stories as well.

**Comment by duttaditya18** [comment]
This works for stories : 
```python
for story in L.get_stories():
    # story is a Story object
    for item in story.get_items():
        # item is a StoryItem object
        L.download_storyitem(item, ':stores')
```

**Comment by duttaditya18** [comment]
This work : 
```python
import json
import instaloader

# id.json with "username" and "password"
with open('id.json') as json_data:
    d = json.load(json_data)

# Get instance
L = instaloader.Instaloader()

# Optionally, login or load session
L.login(d["username"], d["password"])

profile = instaloader.Profile.from_username(L.context, "apooorvaa_")

L.download_profile("apooorvaa_", profile_pic=False, download_stories_only=True)

# fast_update=True doesn't work for some reason. If it did, it would only download the stuff that it doesn't has. It only works in stories.

```

**Comment by duttaditya18** [comment]
See https://github.com/duttaditya18/insta-stalk/blob/master/playground/downloadAllProfile.py

**Comment by duttaditya18** [comment]
Her User ID is `4835530191`. In case that is needed.

**Comment by duttaditya18** [comment]
You can change the User-Agent Header.

This : 
```python
import instaloader

# Log in.

# Get instance
L = instaloader.Instaloader(user_agent="Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36")
```

See [`insta-stalk/playground/followee.py`](https://github.com/duttaditya18/insta-stalk/blob/master/playground/followee.py)
Also see this : https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/User-Agent

**Comment by n1trob4ct3r** [comment]
nice dude!

**Comment by n1trob4ct3r** [comment]
and use someone else's account for testing. It would be really bad if she got to know what you are doing

**Comment by n1trob4ct3r** [comment]
please dont target her. she is not a test subject. I made that testing account for a reason.

**Comment by n1trob4ct3r** [comment]
use that to log in so that we can put it up in the json file to use and not disclose any of our accounts

**Comment by n1trob4ct3r** [comment]
use that to log in so that we can put it up in the json file to use and not disclose any of our accounts

**Comment by n1trob4ct3r** [comment]
instascrape_1 
gimmesudo

**Comment by n1trob4ct3r** [comment]
also, these programs are too slow

**Comment by n1trob4ct3r** [comment]
i think i know how to fix it

**Comment by n1trob4ct3r** [comment]
how about we put all login and profile stuff in  __init__.py and call the other files (eg downloadAll.py) by passing values into them  and receiving return values in the end

**Comment by n1trob4ct3r** [comment]
i think it might speed things up

**Comment by n1trob4ct3r** [comment]
cuz there is a lot of redundancy

**Comment by n1trob4ct3r** [comment]
and I can't push
please add me  to the contributors

**Comment by duttaditya18** [comment]
https://www.quora.com/What-are-the-underlying-reasons-people-stalk-other-people

**Comment by n1trob4ct3r** [comment]
@duttaditya18 yo!

**Comment by n1trob4ct3r** [comment]
@duttaditya18 explain what we have to do next

**Comment by n1trob4ct3r** [comment]
@duttaditya18 we can't download files an keep it on the server as our hosting is most likely to be read only

**Comment by duttaditya18** [comment]
@n1trob4ct3r See this : https://core.telegram.org/bots/api#sending-files

Telegram API has a method which allows uploading files by URL.

**Comment by duttaditya18** [comment]
@n1trob4ct3r Imgur also has an extensible API for this.

We will implement that as well : https://apidocs.imgur.com/
